In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
data = pd.read_csv('Social_Network_Ads.csv')
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [33]:
x = data.iloc[:,1:-1]
x

Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [34]:
x = pd.get_dummies(x, columns=["Gender"])

In [35]:
x

Age  EstimatedSalary  Gender_Female  Gender_Male
0     19            19000              0            1
1     35            20000              0            1
2     26            43000              1            0
3     27            57000              1            0
4     19            76000              0            1
..   ...              ...            ...          ...
395   46            41000              1            0
396   51            23000              0            1
397   50            20000              1            0
398   36            33000              0            1
399   49            36000              1            0

[400 rows x 4 columns]

In [43]:
x = x.values

In [45]:
x.shape

(400, 4)

In [44]:
y = data.iloc[:,-1].values
y.shape

(400,)

## Feature scaling

In [51]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_x = scaler.fit_transform(x, y)
scaled_x

array([[-1.78179743, -1.49004624, -1.02020406,  1.02020406],
       [-0.25358736, -1.46068138, -1.02020406,  1.02020406],
       [-1.11320552, -0.78528968,  0.98019606, -0.98019606],
       ...,
       [ 1.17910958, -1.46068138,  0.98019606, -0.98019606],
       [-0.15807423, -1.07893824, -1.02020406,  1.02020406],
       [ 1.08359645, -0.99084367,  0.98019606, -0.98019606]])

## Train Test Split

In [52]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(scaled_x, y, test_size=0.2)

In [53]:
x_train

array([[ 1.5611621 ,  1.00596657,  0.98019606, -0.98019606],
       [-0.82666613,  0.15438573, -1.02020406,  1.02020406],
       [ 1.08359645, -1.22576253, -1.02020406,  1.02020406],
       ...,
       [-0.34910049,  1.32898   , -1.02020406,  1.02020406],
       [ 2.13424088, -0.69719511,  0.98019606, -0.98019606],
       [-1.49525804, -1.51941109, -1.02020406,  1.02020406]])

In [54]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,

In [55]:
x_test

array([[-0.63563988, -1.51941109, -1.02020406,  1.02020406],
       [ 0.41500455, -0.13926283, -1.02020406,  1.02020406],
       [-0.73115301, -0.2273574 ,  0.98019606, -0.98019606],
       [ 0.31949142,  0.06629116,  0.98019606, -0.98019606],
       [-0.63563988,  0.03692631,  0.98019606, -0.98019606],
       [ 1.46564897, -1.04957339,  0.98019606, -0.98019606],
       [ 0.89257019, -0.66783025,  0.98019606, -0.98019606],
       [ 0.41500455,  0.30121002, -1.02020406,  1.02020406],
       [ 0.98808332, -1.16703281,  0.98019606, -0.98019606],
       [ 0.70154394,  1.7988177 ,  0.98019606, -0.98019606],
       [-0.92217926, -1.1083031 , -1.02020406,  1.02020406],
       [ 0.51051768,  1.74008799, -1.02020406,  1.02020406],
       [ 0.12846516,  0.03692631, -1.02020406,  1.02020406],
       [ 2.03872775,  0.18375059,  0.98019606, -0.98019606],
       [-0.25358736,  0.03692631,  0.98019606, -0.98019606],
       [ 0.31949142, -0.28608712,  0.98019606, -0.98019606],
       [ 0.41500455,  2.

In [56]:
y_test

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

## SVC

In [57]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear' ,random_state=1)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=1)

In [58]:
y_pred = classifier.predict(x_test)

In [59]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]]


##  Confusion Matrix

In [60]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[45,  4],
       [10, 21]], dtype=int64)

In [61]:
accuracy_score(y_test, y_pred)

0.825